name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi  # Optional: matches what you set in PyPI
    permissions:
      id-token: write  # REQUIRED for trusted publishing
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish
