name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run unit tests and collect coverage
        run: uv run pytest -m "not integration"

    #   - name: Upload coverage to Codecov
    #     uses: codecov/codecov-action@v4-beta
    #     with:
    #       flags: smart-tests
    #       verbose: true
    #       file: ./coverage.xml
    #     env:
    #       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
